#!/usr/bin/env ruby
require 'fileutils'

def randomize_secret
  (1..40).map { |x| (65 + rand(26)).chr }.join
end

session_store_file = <<-SESSION_STORE
Railscollab::Application.config.secret_token = '#{randomize_secret}'
SESSION_STORE

# write session store
puts 'Generating session keys'
File.open('config/initializers/session_store.rb', 'w') { |f| f.write(session_store_file) }

# Run normal install scripts
system "bundle install"
system "rake db:migrate && rake db:seed --trace"